[build]
  # Esta línea le dice a Netlify que todo el proyecto web está en la carpeta tcq-web
  base = "tcq-web"
  
  # Comando para instalar dependencias y construir la web
  command = "npm install && npm run build"
  
  # Carpeta donde Vite guarda el resultado final (por defecto es dist)
  publish = "dist"

# Redirección necesaria para que React Router funcione bien en Netlify
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
